# 예외처리

1. 예외 처리의 필요성
    1) 예외(exception) : 개발자가 직접 처리할 수 있는 문제
    2) 오류(error) : 개발자가 처리할 수 없는 문제

    3) 에외 처리의 목적 :
        어떤 문제가 발생했을 때 그 문제를 해결해주는 것이 아니라, 발생된 문제로 인해
        프로그램이 비정상적으로 종료되는 것을 막고, 사용자에게 발생한 문제에 대해 정보를 전달하기 위함.

2. 예외 처리
    1) 고전적 예외 처리
    우리는 커피머신 오타 시 발생하는 오류를 해결하는 로직에서 사용했었다.
if drink == None:
    conti
3. 예외 처리의 종류

```
+------+---------------------+---------------------------------------------+
| 순번 |     예외 클래스     |                     의미                    |
+------+---------------------+---------------------------------------------+
|  1   |    BaseException    |              최상위 예외 클래스             |
|  2   |      Exception      |       대부분 예외 클래스의 슈퍼 클래스      |
|  3   |    AritmeticError   |          산술 연산에 문제가 있을 때         |
|  4   |    AttributeError   |           잘못된 속성을 참조할 때           |
|  5   |       E0FError      | 파일에서 더 이상 읽어 들일 데이터가 없을 때 |
|  6   | ModuleNotFoundError |           import할 모듈이 없을 때           |
|  7   |  FileNotFoundError  |           존재하지 않는 파일일 때           |
|  8   |      IndexError     |          잘못된 인덱스를 사용할 때          |
|  9   |      NameError      |        잘못된 이름(변수)를 사용할 때        |
|  10  |     SyntaxError     |               문법이 틀렸을때               |
|  11  |      TypeError      |   계산하려는 데이터의 유형이 잘못되었을 때  |
|  12  |      ValueError     |     계산하려는 데이터 값이 잘못되었을때     |
+------+---------------------+---------------------------------------------+
```
4. 예외 처리 방식
   1. 모든 예외 처리하는 방식 -> try / except / finally
    ```
    형식:
    try :
        코드 작성 영역
    except : 
        예외 발생 시 처리 영역
    finally :
        언제나 실행되는 영역
    ```
   2. 특정 예외만 처리하는 방식
   ```
   형식:
   try :
    a = int(input("나누는 수 (정수)를 입력하세요 >>> "))
    b = int(input("나누어지는 수 (정수)를 입력하세요 >>> "))
    print(f'b / a = {b / a}')
    except ZeroDivisionError:
        print('0으로 나눌 수 없습니다.')
    except TypeError:
        print('나눌 때 자료형이 일치하지 않습니다.')
    except ValueError:
        print("정수만 입력 할 수 있습니다.")
   ```

   3. else / finally
   try / except 문에 else / finally를 달 수 있는데,
   else : 예외가 발생하지 않으면 처리되는 구문
   finally : 예외 발생 여부와 관계 없이 맨 마지막에 항상 처리되는 구문
    ```python
       try :
           a = int(input("나누어지는 수를 정수로 입력하세요 >>>"))
           b = int(input("나누는 수를 정수로 입력하세요 >>>"))
           result = b / a         # 예외가 발생할 수 있는 구간이 try 문 내에 있어야만 한다.
       except ZeroDivisionError as e:
           print(e)
       except TypeError as e:
           print(e)
       except ValueError as e:
           print(e)
       else:
           print(f'b / a = {result}')
       finally:
           print("프로그램 종료")
    ```
결과적으로 개발자가 고려해야할 것은 일단 try를 써버리면 except 안 썼을 떄 오류가 발생하기 때문에 try / except문이 없는 상태에서 다양하게 검증해보고 어떤 예외가 발생하는지 체크해야 한다.
그리고 그 발생한 예외들에 대한 except문을 작성해야 하고, 정상적으로 처리가 되었을 떄 else 문을 쓸 필요가 있다.

하지만 이상의 사례와 같이 a = 0 을 입력하는 것 자체가 예외를 발생시키지 않고 ,
1. a = 0 이면서,
2. b / a 연산을 시도할 때 ZerodivisionError가 발생하기 때문에.
else 문에 b / a가 포함되어서는 안된다.
그래서 try 문 내에 result = b / a 를 집어넣어줌으로써 그 부분이 예외 없이 통과되었을 때만
연산 결과가 출력될 수 있도록 `print(f'b/a = {result})`로 정리했다.   
    
    4. 강제로 예외를 발생시키기
    어떤 사람이 나이를 정수로 입력 받는 프로개름을 사용한다고 가정했을 때,
    컴퓨터 상으로는(그리고 파이썬 상으로는) -1000이 정수이기 때문에 예외가 발생하지 않는다.( 그래서 우리는 0미만 200초과를 조건문으로 처리하는 것을 학습했다.)
    하지만 -1000살이 되는 것이 불가능하기 때문에 조건문이 아니라 직접 예외를 발생시켜서 처리하는 방법을 학습한다. -> raise문
    ```
    형식 :
    raise 예외클래스()
    
    또는
    raise 예외클래스(예외메세지)
    raise의 경우 강제로 예외를 발생시킨다는 점에서 주로 사용되는 예외 클래스는
     Exception이다.
    '''  
   ```
    ```python
    age = int(input("나이를 입력하세요>>>"))           # - 100을 입력해도 예외가 발생되지 않는다.
    print(f'당신의 나이는 {age}살 입니다.')
    
    try :
        age = age = int(input("나이를 입력하세요>>>"))
        if age < 0 or age > 200:
            raise Exception('강제로 발생시킨 예외입니다.')
    except Exception as e:
        print("발생한 예외 메세지는 다음과 같습니다.")
        print(e)
    
    
    ```
이상의 코드는 특정 예외가 아니라 113번 으로 넘어가기만 해도 바로 예외가 발생해버린다.

   5. 사용자 정의 예외 클래스
   강제로 예외를 발생시키는 예외 클래스를 정의
```python
class Error(Exception):
    pass
```

